### ISSUE TITLE
Opinion regarding webmention ?

### ISSUE THREAD

**Issue by akuckartz** [csarven/linked-data-notifications#1]
I noticed https://indiewebcamp.com/Webmention#Sarven_Capadisli_with_csarven.ca

Any suggestions regarding https://github.com/aaronpk/webmention/issues/39#issuecomment-221962624 ?

/cc @melvincarvalho

**Comment by csarven** [comment]
The article that's work in progress discusses and compares some of the approaches for decentralised notifications, and then explores Solid notifications (spec will follow). Suggestions on that comment is unfortunately out of scope here. However, this article intends to discuss the syntax of various approaches.
