### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by rhiaro** [csarven/linked-data-notifications#2]
* [x] Finish references and footnotes (Sarven)
* [x] Replace schema.org vocab example with something distinctly non-calendary (Sarven)
* [x] Make 15 pages (Sarven: formatting parts)
  * [x] Hide the metadata from "Identifier" to "License" at least in the PDF we submit to ESWC
  * [x] Move all definitions in the "terminology" section inline, i.e. don't start a new line for a new term. Make proper sentences, e.g. "By Decentralisation we mean …". "An Inbox is …"
  * [x] Move "Using this article as the target for notifications, we welcome readers' feedback via LDN." into a footnote and make sure it doesn't take more than one line.
  * [x] Shorten the "Change of State" use cases (e.g. use fewer examples)
  * [x] Shorten every "in order to" to simply "to" (works almost always)
  * [x] Don't duplicate requirements titles but highlight the requirements title where it occurs inline, e.g. change `R1 Modularity … encourage modularity of applications` into `R1 … encourage <strong>modularity</strong> of applications`
  * [x] Tweak the CSS to reduce the space between `<li>` bullet points, like `[nosep]` from the `enumitem` LaTeX package would do
  * [x] make the protocol figure flatter and wider
  * [x] Change the enumerated lists for the protocol description into inline lists like `(1) ... (2) ...`
  * [ ] Cut some whitespace in the listings by creative (but still readable) formatting
  * [x] Move the "various purposes" of dokieli inline.
  * [x] put the videos side-by-side
  * [x] consider removing Fig. 6; the other figures already showcase a lot
  * [ ] make sure that the page before the comparison table is completely filled i.e. no space wasted (if necessary by manually moving the table to the "right" position in the next (sub)section)
* [x] Link to test suite (Sarven)
* [x] Fix OnScreen for screenshot (Amy)
* [x] implementation reports
* [ ] ..

**Comment by clange** [comment]
Oh, I see the removal of URLs in the references is not necessary as they are not printed anyway. I'll revert my change.
